/*
 * Basics of Computer Graphics Exercise
 *
 * DO NOT EDIT THIS FILE!
 */

#ifndef ASSIGNMENT_H
#define ASSIGNMENT_H

#include <iostream>
#include <gl_core_32.hh>

void drawScene( int scene, float runTime );
void initCustomResources();
void deleteCustomResources();

#endif
